// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzrHuXm0Zm5Ilo10_luwW1_GnmX86-Pw',
    appId: '1:317804681516:web:7cb337e6e37c2a2f053489',
    messagingSenderId: '317804681516',
    projectId: 'weatherly-9bdf3',
    authDomain: 'weatherly-9bdf3.firebaseapp.com',
    storageBucket: 'weatherly-9bdf3.appspot.com',
    measurementId: 'G-TKLGDBR66Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsG6D8UHBIZ0bzNqj6kmcDHUSHZJ8TaU',
    appId: '1:317804681516:android:31e915f7a5ecaa51053489',
    messagingSenderId: '317804681516',
    projectId: 'weatherly-9bdf3',
    storageBucket: 'weatherly-9bdf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZF2cP5_g8piuoTFiDZ6QnXZ9hgYHq9Y',
    appId: '1:317804681516:ios:b2ff2e9b6e400c39053489',
    messagingSenderId: '317804681516',
    projectId: 'weatherly-9bdf3',
    storageBucket: 'weatherly-9bdf3.appspot.com',
    iosBundleId: 'com.example.skyviewWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZF2cP5_g8piuoTFiDZ6QnXZ9hgYHq9Y',
    appId: '1:317804681516:ios:c8f12c1289f269ac053489',
    messagingSenderId: '317804681516',
    projectId: 'weatherly-9bdf3',
    storageBucket: 'weatherly-9bdf3.appspot.com',
    iosBundleId: 'com.example.skyviewWeatherApp.RunnerTests',
  );
}
